# pre-commit install --install-hooks --overwrite
# pre-commit autoupdate
# pre-commit run --all-files

default_stages: [ pre-commit ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '^version.txt$'
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [ "--unsafe" ]
      - id: debug-statements
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
        exclude: '^data/example.env$'
      - id: check-illegal-windows-names

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff
      - id: ruff-format
